## Site Settings
## Technical

email: 'kontakt@hierofania.pl'
url: 'http://hierofania.pl'
excerpt_separator: '<!--more-->'
# base_url:  'http://sylar66.github.io/Hierofania/'
 
##Authoring
title: 'HIEROFANIA'
name: 'Hierofania' 
tagline: 'Coś Się Święci'
description: "Hierofania - objawienie się świętości, każde wtargnięcie sacrum w sferę profanum; kluczowy termin w teorii religii M. Eliadego. Przestrzeń człowieka Eliade podzielił na dwa typy: przestrzeń sacrum i profanum - zaznaczył, że sfery te mogą się pokrywać (gdyż sfera sacrum jest sferą, która jest konstytuowana przez nasz umysł). Prostym przykładem sfery sacrum jest np. kościół, który dla osoby konkretnego wyznania jest miejscem w którym objawia się świętość - dla ateisty zaś jest zwykłym budynkiem (sferą profanum)."
author: Joanna Słonka
admin: Krystian Okaz


##Gems
gems:
  - jekyll-sitemap


#Social Media

twitter_username: HierofaniaPL


#Build Settings
##Backend
highlighter:  rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
##Frontend
paginate: 5
paginate_path: "/blog/page:num/"

sass:
    sass_dir: _sass
#permalink: /blog/:title

  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
prose:
  ignore: ['_includes','_layouts','_sass','_scss','css','js','_config.yml','.gulpfile.js',]
  siteurl: 'http://hierofania.pl'
  media: 'img'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "article"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          alterable: true
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Religia"
              value: "religia"
            - name: "Islam"
              value: "islam"
            - name: "Chrześcijaństwo"
              value: "chrześcijaństwo"
            - name: "Koran"
              value: "koran"
            - name: "Męczennicy"
              value: "męczennicy"
            - name: "Katolicyzm"
              value: "katolicyzm"
            - name: "Żydzi"
              value: "żydzi"
            - name: "Monoteizm"
              value: "monoteizm"
            - name: "Politeizm"
              value: "politeizm"
            - name: "Prześladowania"
              value: "prześladowania"
            - name: "Wojna"
              value: "wojna"
            - name: "Relikwia"
              value: "relikwia"
            - name: "Herezja"
              value: "herezja"
            - name: "Inkwizycja"
              value: "inkwizycja"
            - name: "Protestantyzm"
              value: "protestantyzm"
            - name: "Antysemityzm"
              value: "antysemityzm"
            - name: "Tora"
              value: "tora"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
    _posts/blog:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""


