## Site Settings
## Technical

email: 'kontakt@hierofania.pl'
base_url:  'http://sylar66.github.io/Hierofania/'
url: 'http://HIEROFANIA.pl'
excerpt_separator: '<!--more-->'

 
##Authoring
title: 'HIEROFANIA'
name: 'Hierofania' 
tagline: 'Coś Się Święci'
description: "Hierofania - objawienie się świętości, każde wtargnięcie sacrum w sferę profanum; kluczowy termin w teorii religii M. Eliadego. Przestrzeń człowieka Eliade podzielił na dwa typy: przestrzeń sacrum i profanum - zaznaczył, że sfery te mogą się pokrywać (gdyż sfera sacrum jest sferą, która jest konstytuowana przez nasz umysł). Prostym przykładem sfery sacrum jest np. kościół, który dla osoby konkretnego wyznania jest miejscem w którym objawia się świętość - dla ateisty zaś jest zwykłym budynkiem (sferą profanum)."
author: Joanna Słonka
admin: Krystian Okaz



#Social Media

twitter_username: HierofaniaPL


#Build Settings

#markdown: redcarpet
highlighter:  rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]

paginate: 4
paginate_path: "/blog/page:num/"
#permalink: /blog/:title


prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
