## Site Settings
## Technical

email: 'kontakt@hierofania.pl'
base_url:  'http://sylar66.github.io/Hierofania/'
url: 'http://HIEROFANIA.pl'
excerpt_separator: '<!--more-->'

 
##Authoring
title: 'HIEROFANIA'
name: 'Hierofania' 
tagline: 'Coś Się Święci'
description: "Hierofania - objawienie się świętości, każde wtargnięcie sacrum w sferę profanum; kluczowy termin w teorii religii M. Eliadego. Przestrzeń człowieka Eliade podzielił na dwa typy: przestrzeń sacrum i profanum - zaznaczył, że sfery te mogą się pokrywać (gdyż sfera sacrum jest sferą, która jest konstytuowana przez nasz umysł). Prostym przykładem sfery sacrum jest np. kościół, który dla osoby konkretnego wyznania jest miejscem w którym objawia się świętość - dla ateisty zaś jest zwykłym budynkiem (sferą profanum)."
author: Joanna Słonka
admin: Krystian Okaz



#Social Media

twitter_username: HierofaniaPL


#Build Settings

#markdown: redcarpet
highlighter:  rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]

paginate: 4
paginate_path: "/blog/page:num/"
#permalink: /blog/:title


# PROSE Configuration
prose:
  siteurl: 'http://hmfaysal.github.io/Notepad/'
  relativeLinks: 'http://hmfaysal.github.io/Notepad/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


#include: [".htaccess"]
#exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
#Status API Training Shop Blog About
